[build]
  publish = "public/"
  command = "gatsby build"
  [[plugins]]
  package = "netlify-plugin-gatsby-cache"


[build.environment]
  YARN_VERSION = "1.3.2"
  YARN_FLAGS = "--no-ignore-optional"
  NODE_OPTIONS = "--max_old_space_size=4096"
